language: java
jdk:
- openjdk9
sudo: false
script: mvn clean install
deploy:
  provider: releases
  api_key:
    secure: Xsz6jYacGz7vRCLqoBwhrom3ECOd5jsJ93VdT95A+RM2qAW5RnuGVJF3EVrUour2XKe+6rpbZHcA8Si23kYmO1HCk0O6V4VW5R73mjwBO1e7io9emDeQuX7rsWqlKlaWf0+TKJcFA2vZIai3OiDZxxtNXoS/D9vdzLhdkZdtbS6TgDs25Pf8N9V9OUOKRuvXLATv6f+jDp8ntwBD/jtiDVVNvFvqzJfMr39zbJ4/Pec28X+TTfDiy7NAsfoDjKGfxziUp1ZH0FiTLwQncH617LDHsN6Ime1dzYaXU8bGUqTIFDo9q4Ia7joE5Ran7KyVORqXvRZN53V8Pe6LAwcQxDiHPXR0NUEHKkfgPWVHa2vU/OdGDDMKwReY55ykUbDOX4y/r8LMAuxCNi8AmqvYd1fu8z2+mUViHcqOFqGQZ5wUed9Qs8fEpuh6okEDroTu80rIh7WhLJQKA8Ux4rldzmSbLfqwbCIzJOEMBtjUBTyYtIjp+1TtLxik9BnNA+W9SdqVoQZeFjQ5TX0TUgXoizL1mnqFsShwVA2Ec/5EDjixIzTrt1Y1MHL4hIj6aBGNH28oTZhBaVw5oCk61AbqDgDCoUxtOA0QBugoMsDNhXSWsjkso2NM6T4/+kDzw351MUildzrkF51p4bOitRHRm56C1NwqukMr4PR/OVQBb1s=
  file: target/asm3.zip
  skip_cleanup: true
  on:
    tags: true
    repo: hneemann/Assembler
